// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADYXLhBQK0XsdviT_fyGRBNaO2nzAOcOg',
    appId: '1:309676427106:web:ac4bf6c4503301b590ce3b',
    messagingSenderId: '309676427106',
    projectId: 'eventes-dd7bd',
    authDomain: 'eventes-dd7bd.firebaseapp.com',
    storageBucket: 'eventes-dd7bd.appspot.com',
    measurementId: 'G-2ZGMY8LFJX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCz94vg22OhaffDEkP24r-5TlC6cySwt2Q',
    appId: '1:309676427106:android:d13ae0e31507747490ce3b',
    messagingSenderId: '309676427106',
    projectId: 'eventes-dd7bd',
    storageBucket: 'eventes-dd7bd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgLy9-zTWhUSRE3ioagU7y29ZpH0IMGYQ',
    appId: '1:309676427106:ios:9206e1533a409d5190ce3b',
    messagingSenderId: '309676427106',
    projectId: 'eventes-dd7bd',
    storageBucket: 'eventes-dd7bd.appspot.com',
    iosClientId: '309676427106-nvr9ot6ioknp0bakd1lgrudndhhunalt.apps.googleusercontent.com',
    iosBundleId: 'com.techgebra.evantez',
  );
}
